export const data = [
  {
    name: "Abrar Shaikh",
    role: "Manager",
    designation: "TopManagement",
    email: "abrar.shaikh@example.com",
    company: "ABC Corp",
    department: "TopManagement",
    phone: "+1234567890",
    address: "123 Main St, Cityville",
    dateOfBirth: "1975-02-15",
    reports: [
      {
        name: "Kashif Shaikh",
        role: "Co-Founder & CEO",
        designation: "Management",
        email: "kashif.shaikh@example.com",
        company: "ABC Corp",
        department: "Management",
        phone: "+1234567891",
        address: "456 Elm St, Cityville",
        dateOfBirth: "1980-08-12",
        reports: [
          {
            name: "Aaron Pires",
            role: "Deputy Manager - Sales and Business Strategy",
            designation: "Sales & Business Development",
            email: "aaron.pires@example.com",
            company: "ABC Corp",
            department: "Sales & Business Development",
            phone: "+1234567892",
            address: "789 Oak St, Cityville",
            dateOfBirth: "1988-03-22",
            reports: [],
          },
          {
            name: "Narshiva Naik",
            role: "Deputy Manager - Finance",
            designation: "Finance",
            email: "narshiva.naik@example.com",
            company: "ABC Corp",
            department: "Finance",
            phone: "+1234567893",
            address: "234 Maple St, Cityville",
            dateOfBirth: "1985-11-30",
            reports: [
              {
                name: "Hema Natalkar",
                role: "Associate - Finance",
                designation: "Finance",
                email: "hema.natalkar@example.com",
                company: "ABC Corp",
                department: "Finance",
                phone: "+1234567894",
                address: "567 Birch St, Cityville",
                dateOfBirth: "1990-07-16",
                reports: [],
              },
              {
                name: "Rhutvik Durgadas Sawant",
                role: "Assistant Manager",
                designation: "Finance",
                email: "rhutvik.sawant@example.com",
                company: "ABC Corp",
                department: "Finance",
                phone: "+1234567895",
                address: "890 Pine St, Cityville",
                dateOfBirth: "1992-05-10",
                reports: [],
              },
              {
                name: "Siddhi Mahesh Naik Vernekar",
                role: "Finance Intern",
                designation: "Finance",
                email: "siddhi.naik@example.com",
                company: "ABC Corp",
                department: "Finance",
                phone: "+1234567896",
                address: "123 Cedar St, Cityville",
                dateOfBirth: "1998-09-25",
                reports: [],
              },
            ],
          },
        ],
      },
      {
        name: "Nasreen Abrar Shaikh",
        role: "Director",
        designation: "Management",
        email: "nasreen.shaikh@example.com",
        company: "ABC Corp",
        department: "Management",
        phone: "+1234567897",
        address: "234 Spruce St, Cityville",
        dateOfBirth: "1978-10-05",
        reports: [],
      },
      {
        name: "Ragesh A C",
        role: "Chief of Staff",
        designation: "Head Human Resources & Admin",
        email: "ragesh.ac@example.com",
        company: "ABC Corp",
        department: "Human Resources",
        phone: "+1234567898",
        address: "345 Fir St, Cityville",
        dateOfBirth: "1973-12-19",
        reports: [
          {
            name: "Amol Kakade",
            role: "Deputy Manager - General Operations & Activation",
            designation: "Maintenance",
            email: "amol.kakade@example.com",
            company: "ABC Corp",
            department: "Maintenance",
            phone: "+1234567899",
            address: "678 Poplar St, Cityville",
            dateOfBirth: "1985-04-02",
            reports: [],
          },
          {
            name: "Melisa Fernandes",
            role: "Associate - Front Office & Admin",
            designation: "Administration",
            email: "melisa.fernandes@example.com",
            company: "ABC Corp",
            department: "Administration",
            phone: "+1234567800",
            address: "901 Willow St, Cityville",
            dateOfBirth: "1992-12-11",
            reports: [],
          },
          {
            name: "Pranali Kandolkar",
            role: "Sr. Associate - Community & Admin",
            designation: "Administration",
            email: "pranali.kandolkar@example.com",
            company: "ABC Corp",
            department: "Administration",
            phone: "+1234567801",
            address: "345 Palm St, Cityville",
            dateOfBirth: "1987-08-24",
            reports: [
              {
                name: "Naaz Parveen Bavannawar",
                role: "Jr. Executive - Receptionist",
                designation: "Administration",
                email: "naaz.bavannawar@example.com",
                company: "ABC Corp",
                department: "Administration",
                phone: "+1234567802",
                address: "567 Aspen St, Cityville",
                dateOfBirth: "1996-10-13",
                reports: [],
              },
              {
                name: "Anne Fernandes",
                role: "Associate - Community & Admin",
                designation: "Administration",
                email: "anne.fernandes@example.com",
                company: "ABC Corp",
                department: "Administration",
                phone: "+1234567803",
                address: "890 Redwood St, Cityville",
                dateOfBirth: "1993-01-20",
                reports: [],
              },
            ],
          },
          {
            name: "Urjita Sangodkar",
            role: "Associate - Community & Admin",
            designation: "Administration",
            email: "urjita.sangodkar@example.com",
            company: "ABC Corp",
            department: "Administration",
            phone: "+1234567804",
            address: "123 Banyan St, Cityville",
            dateOfBirth: "1991-06-05",
            reports: [],
          },
        ],
      },
      {
        name: "Machindranath Parkar",
        role: "General Manager - IT and Admin",
        designation: "Information Technology",
        email: "machindranath.parkar@example.com",
        company: "ABC Corp",
        department: "Information Technology",
        phone: "+1234567805",
        address: "456 Walnut St, Cityville",
        dateOfBirth: "1975-07-08",
        reports: [
          {
            name: "Dasmon Goes",
            role: "Jr. Network Engineer",
            designation: "Information Technology",
            email: "dasmon.goes@example.com",
            company: "ABC Corp",
            department: "Information Technology",
            phone: "+1234567806",
            address: "678 Alder St, Cityville",
            dateOfBirth: "1994-10-29",
            reports: [],
          },
          {
            name: "Faizan Shaikh",
            role: "Executive - IT Dept (Band 4B)",
            designation: "Information Technology",
            email: "faizan.shaikh@example.com",
            company: "ABC Corp",
            department: "Information Technology",
            phone: "+1234567807",
            address: "789 Spruce St, Cityville",
            dateOfBirth: "1995-09-21",
            reports: [],
          },
          {
            name: "Rajiv Kumar Pal",
            role: "Sr. Network Engineer",
            designation: "Information Technology",
            email: "rajiv.pal@example.com",
            company: "ABC Corp",
            department: "Information Technology",
            phone: "+1234567808",
            address: "123 Poplar St, Cityville",
            dateOfBirth: "1991-11-11",
            reports: [],
          },
        ],
      },
      {
        name: "Benson Nadakattin",
        role: "Deputy Manager - Kaffe Operations",
        designation: "Café",
        email: "benson.nadakattin@example.com",
        company: "ABC Corp",
        department: "Café",
        phone: "+1234567809",
        address: "234 Willow St, Cityville",
        dateOfBirth: "1983-02-28",
        reports: [
          {
            name: "Maher Bangui",
            role: "Associate - General Operations",
            designation: "Café",
            email: "maher.bangui@example.com",
            company: "ABC Corp",
            department: "Café",
            phone: "+1234567810",
            address: "345 Cedar St, Cityville",
            dateOfBirth: "1990-08-17",
            reports: [],
          },
          {
            name: "Raju Arolkar",
            role: "Commis 1",
            designation: "Café",
            email: "raju.arolkar@example.com",
            company: "ABC Corp",
            department: "Café",
            phone: "+1234567811",
            address: "456 Maple St, Cityville",
            dateOfBirth: "1988-01-15",
            reports: [],
          },
          {
            name: "Shyam Sundar",
            role: "Commis 1",
            designation: "Café",
            email: "shyam.sundar@example.com",
            company: "ABC Corp",
            department: "Café",
            phone: "+1234567812",
            address: "789 Birch St, Cityville",
            dateOfBirth: "1986-09-07",
            reports: [],
          },
          {
            name: "Kritesh Gawde",
            role: "Customer Service Executive (C.S.E)",
            designation: "Café",
            email: "kritesh.gawde@example.com",
            company: "ABC Corp",
            department: "Café",
            phone: "+1234567813",
            address: "901 Redwood St, Cityville",
            dateOfBirth: "1992-03-30",
            reports: [],
          },
        ],
      },
      {
        name: "Kalpesh Naik",
        role: "Senior Product & UI/UX Developer",
        designation: "Tech",
        email: "kalpesh.naik@example.com",
        company: "ABC Corp",
        department: "Tech",
        phone: "+1234567814",
        address: "567 Palm St, Cityville",
        dateOfBirth: "1989-04-04",
        reports: [
          {
            name: "Aiwinraj KS",
            role: "Web Developer Intern",
            designation: "Tech",
            email: "aiwinraj.ks@example.com",
            company: "ABC Corp",
            department: "Tech",
            phone: "+1234567815",
            address: "678 Cedar St, Cityville",
            dateOfBirth: "1998-05-18",
            reports: [],
          },
          {
            name: "Allan Mark Silveira",
            role: "Web Developer Intern",
            designation: "Tech",
            email: "allan.silveira@example.com",
            company: "ABC Corp",
            department: "Tech",
            phone: "+1234567816",
            address: "789 Walnut St, Cityville",
            dateOfBirth: "1999-07-25",
            reports: [],
          },
          {
            name: "Anushri Mohandas Bhagat",
            role: "Web Developer Intern",
            designation: "Tech",
            email: "anushri.bhagat@example.com",
            company: "ABC Corp",
            department: "Tech",
            phone: "+1234567817",
            address: "890 Willow St, Cityville",
            dateOfBirth: "1997-12-02",
            reports: [],
          },
          {
            name: "Sankalp Chandrashekar Kalangutkar",
            role: "Web Developer Intern",
            designation: "Tech",
            email: "sankalp.kalangutkar@example.com",
            company: "ABC Corp",
            department: "Tech",
            phone: "+1234567818",
            address: "234 Oak St, Cityville",
            dateOfBirth: "1996-11-09",
            reports: [],
          },
        ],
      },
      {
        name: "Nikhil Nagvekar",
        role: "Associate - Community & Marketing",
        designation: "Marketing",
        email: "nikhil.nagvekar@example.com",
        company: "ABC Corp",
        department: "Marketing",
        phone: "+1234567819",
        address: "456 Spruce St, Cityville",
        dateOfBirth: "1994-06-16",
        reports: [],
      },
      {
        name: "Farzeen Qadri",
        role: "Executive Assistant",
        designation: "Executive Management",
        email: "farzeen.qadri@example.com",
        company: "ABC Corp",
        department: "Executive Management",
        phone: "+1234567820",
        address: "567 Fir St, Cityville",
        dateOfBirth: "1987-03-05",
        reports: [],
      },
    ],
  },
];
